spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/job_board
    username: postgres
    password: 1234567890
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 8080
